name: GitHub Readme YouTube Cards
on:
  schedule:
    # At 12 AM, only Friday
    - cron: "0 0 * * FRI"
  workflow_dispatch:

jobs:
  build: youtube-cards
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCipSxT7a3rn81vGLw9lqRkgUCKdQsIxFPr4Huz29FUvcEGw
          - run: echo OUTPUT '${{ steps.youtube-cards.outputs.markdown }}'
        shell: bash